### ISSUE TITLE
Doesn't convert Twitter Bootstrap page properly

### ISSUE THREAD

**Issue by mape** [aaronpowell/html2jade-website#1]
When running http://twitter.github.com/bootstrap/base-css.html through http://html2jade.aaron-powell.com/ the output isn't valid jade.

For example it takes the text mentions of "code" and turns those into code tags which breaks the page.

**Comment by aaronpowell** [comment]
I don't actually work on the html2jade library, you'd be best raising the issue with them - https://github.com/donpark/html2jade
