### ISSUE TITLE
The API is not working

### ISSUE THREAD

**Issue by dflourusso** [aaronpowell/html2jade-website#10]
Post:
`curl -X POST --data "<div></div>" "http://html2jade.aaron-powell.com/convert"` 

Error:

```
<!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
```

**Comment by aaronpowell** [comment]
FWIW there isn't really an API, that's just the URL which the site uses to do its own stuff. Using it outside the browser isn't a supported scenario (it should work, but if it doesn't, oh well).

**Comment by jstangroome** [comment]
Try:
`curl -X POST --data "html=<div></div>" "http://html2jade.aaron-powell.com/convert"`

**Comment by dflourusso** [comment]
Very good, it works fine. Thanks
