### ISSUE TITLE
Upgrade to latest version of html2jade

### ISSUE THREAD

**Issue by jksdua** [aaronpowell/html2jade-website#2]
The latest version contains many fixes.  I was trying to convert some html markup yesterday and noticed it appends a . if there is an empty class which does not render correctly.  The latest html2jade version fixes this issue.

**Comment by wlaurance** [comment]
:+1:

**Comment by lacymorrow** [comment]
Yep. Getting some deprecated code being spit out.

**Comment by aaronpowell** [comment]
After waaaaaaaaaaaaaaaaaaay too long this is done!
