### ISSUE TITLE
Pack website with AppJS

### ISSUE THREAD

**Issue by Grawl** [aaronpowell/html2jade-website#3]
Can you pack html2jade-website with [AppJS](https://github.com/appjs/appjs/)? Is an SDK for Node.js apps. For example, [Brackets](http://brackets.io/) use it.

**Comment by aaronpowell** [comment]
I see no point to this, if you need to convert HTML to Jade offline you can use the Node.js package - https://github.com/donpark/html2jade (it's what the website uses under the hood)

**Comment by Grawl** [comment]
I hate command line, I want UI for this.
