### ISSUE TITLE
Bad nesting conversion

### ISSUE THREAD

**Issue by stephenmathieson** [aaronpowell/html2jade-website#4]
the html:

``` html
<div id="foo">
  <h1>Hello world</h1>
  <div id="bar">
    <p>Blah blah blah</p>
  </div>
</div>
```

produces this jade:

``` jade
#foo
    h1 Hello world
      #bar
        p Blah blah blah
```

Note that in the html, `div#bar` is _not_ a child of the `h1`.

**Comment by colelawrence** [comment]
I have the same issue, I believe this is a bug in html2jade and not this demo website.

**Comment by colelawrence** [comment]
One way to solve this is to surround the code with `<html><body>` and `</body></html>` but this will break regardless on the newest version of html2jade

**Comment by colelawrence** [comment]
![image](https://cloud.githubusercontent.com/assets/2925395/3106618/6fdb287a-e67d-11e3-93c4-627b9a67f1ed.png)

**Comment by mplewis** [comment]
Here's one I found:

``` html
<script src="/ace-builds/src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
<script>
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/monokai");
    editor.getSession().setMode("ace/mode/javascript");
</script>
```

turns into:

``` javascript
script(src='/ace-builds/src-noconflict/ace.js', type='text/javascript', charset='utf-8')
  script
      var editor = ace.edit("editor");
      editor.setTheme("ace/theme/monokai");
      editor.getSession().setMode("ace/mode/javascript");
```

**Comment by aaronpowell** [comment]
Updated to the latest html2jade so now this will be sorted.

**Comment by colelawrence** [comment]
Note that the newest version of html2jade still does not address this issue.

**Comment by aaronpowell** [comment]
I'd say this is a problem with html2jade /cc @donpark

**Comment by donpark** [comment]
I'll take a look.

**Comment by donpark** [comment]
version 0.8.1 generates the following which, except for unnecessary piped text inserted to preserve whitespace, looks correct.

```
html
  body
    #foo
      h1 Hello world
      |   
      #bar
        p Blah blah blah
```

**Comment by donpark** [comment]
This is what 0.8.1 generates with second example:

```
script(src='/ace-builds/src-noconflict/ace.js', type='text/javascript', charset='utf-8')
script.
  var editor = ace.edit("editor");
  editor.setTheme("ace/theme/monokai");
  editor.getSession().setMode("ace/mode/javascript");
```

**Comment by donpark** [comment]
Just confirmed that even http://html2jade.aaron-powell.com/ generates correct output now.
Closing at html2jade end as well.

**Comment by aaronpowell** [comment]
Thanks @donpark. It's good to have the site running the latest version again :wink:
