### ISSUE TITLE
Depracated Doctype rendering

### ISSUE THREAD

**Issue by yowainwright** [aaronpowell/html2jade-website#6]
Great product. The rendering for Doctype is deprecated. 
!!! 5 creates error

**Comment by aaronpowell** [comment]
This is likely to be caused by the really out dated version of html2jade that the website runs. Unfortunately it relies on JSDom which doesn't work on Windows and I don't have a non-Windows machine I can develop on.

**Comment by yowainwright** [comment]
Got it. Still works great. -Thanks

**Comment by aaronpowell** [comment]
Updated the site to use html2jade 0.8.1, that'll fix this.
