### ISSUE TITLE
Doesn't work at all on http://html2jade.aaron-powell.com/

### ISSUE THREAD

**Issue by RedactedProfile** [aaronpowell/html2jade-website#8]
Provided

```
<!doctype html>
<html>
<head>
    <link type="text/css" rel="stylesheet" href="/site.css" />
    <title>test</title>
</head>
<body>
    <h1>A Big Ol Test</h1>
</body>
</html>
```

and got back

```
doctype html
html
  head
    link(type='text/css', rel='stylesheet', href='/site.css')
    |     
    title test
  body
    h1 Hello world!
```

**Comment by RedactedProfile** [comment]
Also worth noting, I provided a totally different document, and still got back that jade sample

**Comment by aaronpowell** [comment]
Hmm I think there must be a problem with the way I'm working with CodeMirror. If you submit then re-focus on the editor, then click the submit again it seems to work. I'll have to have a look back into it.

**Comment by RedactedProfile** [comment]
Sounds good :) im sorry to have to report this ^^;

**Comment by aaronpowell** [comment]
Should be all good now, I was reading out of the form not out of the CodeMirror instance, which it's now doing.

**Comment by RedactedProfile** [comment]
it absolutely does :)

Cheers!
